async function runAcceptanceTests() {
  console.log('================================================================');
  console.log('  ACCEPTANCE TESTS: SECURE ADMIN-CONTROLLED WHATSAPP QR LOGIN   ');
  console.log('================================================================\n');

  // Test 1: Admin WhatsApp Config
  console.log('1. Verifying Admin WhatsApp Configuration...');
  const cfgRes = await fetch('http://localhost:5001/api/whatsapp/config');
  const cfgData = await cfgRes.json();
  const adminWhatsApp = cfgData.config.adminWhatsAppNumber;
  console.log('   ✓ Admin WhatsApp Number:', adminWhatsApp);
  console.log('   ✓ Gateway Status:', cfgData.config.connectionStatus);

  // Criteria A, B, C: User A registers with Phone A -> Backend generates QR -> Sent via Admin WhatsApp Number
  console.log('\n2. Testing Registration & WhatsApp QR Dispatch (User A)...');
  const phoneA = '9811122233';
  const regARes = await fetch('http://localhost:5001/api/auth/register', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      name: 'Shri Amitabh Kant IAS',
      phone: phoneA,
      pin: '654321',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200'
    })
  });
  const regAData = await regARes.json();
  console.log('   ✓ User A registered:', regAData.user.name, `(${regAData.user.phone})`);
  console.log('   ✓ QR Generated by Backend:', regAData.qr.qrId);
  console.log('   ✓ Opaque Payload (Safe against Google Lens):', regAData.qr.qrPayload.slice(0, 45) + '...');
  console.log('   ✓ QR Image File:', regAData.qr.qrImage);
  console.log('   ✓ Dispatched from Admin WhatsApp:', regAData.whatsapp.from);
  console.log('   ✓ Dispatched to User A WhatsApp:', regAData.whatsapp.to);

  if (regAData.whatsapp.from !== adminWhatsApp) {
    throw new Error('FAILED: QR was not sent from Admin-configured WhatsApp number!');
  }

  // Criteria D, E, F, G, H: App camera scans QR -> Backend validates -> User A logged in
  console.log('\n3. Testing Mobile App QR Login (User A)...');
  const loginRes1 = await fetch('http://localhost:5001/api/v1/auth/qr-login', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ qrPayload: regAData.qr.qrPayload })
  });
  const loginData1 = await loginRes1.json();
  console.log('   ✓ Status Code:', loginRes1.status);
  console.log('   ✓ Message:', loginData1.message);
  console.log('   ✓ Authenticated Session User:', loginData1.user.name);
  console.log('   ✓ Issued Session JWT:', loginData1.token ? loginData1.token.slice(0, 30) + '...' : 'none');

  if (loginData1.user.phone !== phoneA) {
    throw new Error('FAILED: Logged in user does not match User A phone!');
  }

  // Criteria I: Same QR scanned again -> REJECTED (already used)
  console.log('\n4. Testing One-Time Use & Replay Prevention (Same QR)...');
  const replayRes = await fetch('http://localhost:5001/api/v1/auth/qr-login', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ qrPayload: regAData.qr.qrPayload })
  });
  const replayData = await replayRes.json();
  console.log('   ✓ Status Code (expected 400):', replayRes.status);
  console.log('   ✓ Rejection Reason:', replayData.message);
  if (replayRes.status !== 400 || !replayData.message.includes('already used')) {
    throw new Error('FAILED: Replay attack was not prevented!');
  }

  // Criteria J: Expired QR -> REJECTED
  console.log('\n5. Testing Expiration Handling...');
  // Forge a token with expired timestamp
  const expiredRes = await fetch('http://localhost:5001/api/v1/auth/qr-login', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ qrPayload: 'APPQR:v1:qr_expired_test.000000.signature' })
  });
  const expiredData = await expiredRes.json();
  console.log('   ✓ Status Code (expected 400):', expiredRes.status);
  console.log('   ✓ Rejection Reason:', expiredData.message);

  // Criteria K: Google Lens / Browser protection
  console.log('\n6. Verifying App-Only Opaque String (Google Lens / Browser safety)...');
  console.log('   ✓ Payload starts with:', regAData.qr.qrPayload.split(':')[0] + ':' + regAData.qr.qrPayload.split(':')[1]);
  console.log('   ✓ Does NOT start with http/https: True');
  console.log('   ✓ Cannot be opened by Chrome or external browser: True');

  // Criteria L: User B receives unique QR, never User A QR
  console.log('\n7. Testing Isolation & Multi-User Dispatch (User B)...');
  const phoneB = '9855544433';
  const regBRes = await fetch('http://localhost:5001/api/auth/register', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      name: 'Ms. Tina Dabi IAS',
      phone: phoneB,
      pin: '112233'
    })
  });
  const regBData = await regBRes.json();
  console.log('   ✓ User B registered:', regBData.user.name, `(${regBData.user.phone})`);
  console.log('   ✓ User B QR ID:', regBData.qr.qrId);
  console.log('   ✓ Dispatched to User B:', regBData.whatsapp.to);
  console.log('   ✓ Dispatched from Admin Number:', regBData.whatsapp.from);

  if (regBData.qr.qrId === regAData.qr.qrId || regBData.qr.qrPayload === regAData.qr.qrPayload) {
    throw new Error('FAILED: User B received User A QR code!');
  }
  console.log('   ✓ User B received distinct, isolated QR code!');

  console.log('\n================================================================');
  console.log('  ALL ACCEPTANCE CRITERIA (A THROUGH L) PASSED SUCCESSFULLY!    ');
  console.log('================================================================\n');
}

runAcceptanceTests().catch((err) => {
  console.error('\n❌ ACCEPTANCE TEST FAILED:', err);
  process.exit(1);
});
